site_name: conference
repo_url: https://github.com/Team-Farr/conference
repo_name: conference

theme:
  name: material
  font: true

  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: "#"